Add contributing guide and code of conduct
codeedu/codeedu-plataforma-desafios pull request #7
Opened 2020-04-09 01:44 UTC by fabianoleittes

Let's add a contributing and code of conduct file, so we can work better, together!

2020-04-09 01:54 UTC, fabianoleittes commented
To help review the coding process, I think this guide can help.

https://github.com/thoughtbot/guides/tree/master/code-review

2020-04-09 13:08 UTC, wesleywillians requested changes
Olá Fabiano, como esse projeto tem o objetivo de focar no aprendizado de brazucas e também sabemos que muitos que poderiam estar aprendendo ainda não dominam inglês, estamos querendo utilizar o português como meio de comunicação. Pode parecer estranho para quem já tem mais experiência, mas nesse momento estamos focando mais no aprendizado da linguagem . Se você tiver algo parecido em portuga, ficaria muito feliz em adicionar ;)

2020-04-09 21:31 UTC, fabianoleittes commented
Tranquilo @wesleywillians eu vou traduzir esse guide com maior prazer. 😉

2020-04-09 23:24 UTC, fabianoleittes commented
@wesleywillians ajuste feito para pt_br, fique a vontade para sugerir melhorias ou até mesmo adicionar novas categorias.
Só gostaria de deixar claro, que essa é só uma sugestão de um guide de como contribuir para o projeto. abs!

2020-04-10 19:24 UTC, wesleywillians commented
Fabiano, consegue abrir uma nova PR apenas com o novo código de conduta para eu ajustar? Você acabou misturando na mesma um ajuste no arquivo db.go e vai dar conflito com meu última PR. Eu praticamente reelaborei o db.go.

2020-04-10 21:48 UTC, fabianoleittes commented
@wesleywillians está feito, não foi necessário abrir um novo PR. se precisar de mais algum ajuste, me avise.

2020-04-12 00:23 UTC, wesleywillians commented
Fabiano, muito legal. Há alguns ajustes pequenos.

* Resolvi por hora e fins didáticos remover o client, logo podes cortar a menção.
* O mais importante é executar os testes antes de fazer a pr. Basta dar um um go test ./...
* Estamos utilizando por padrão o Github Actions como CI, logo, os testes serão executados sempre que uma PR for criada
* Adicione o Link do processo de contribuição no README principal do projeto.

Valeu! Espero uns PRs em go ;)

2020-04-13 17:44 UTC, fabianoleittes commented
@wesleywillians feito :muscle:

2020-04-16 02:59 UTC, merged