update function user.validate
codeedu/codeedu-plataforma-desafios pull request #8
Opened 2020-04-09 11:52 UTC by chapzin

Referente issues #5

2020-04-09 13:11 UTC, wesleywillians requested changes
Estou mais do que feliz com sua contribuição. Como teremos que validar muita coisa no projeto, o que acha de utilizarmos um pacote de validação mais completo para nos ajudar?

Consegue quebrar a cabeça e tentar implementar esse aqui?

https://github.com/asaskevich/govalidator

2020-04-09 13:38 UTC, chapzin commented
Muito bom, já usei o govalidator criando uma classe pra validações genericas. Vou ver se implemento um aqui interessante.

2020-04-09 15:24 UTC, mihailov-vf commented
Olá tenho muito interesse entender sobre este assunto e de realizar uma boa separação de responsabilidades e gostaria de aprender mais com vocês.

Se fosse para dar uma sugestão, acredito que a sanitização e validações de entrada de dados deveriam ficar no código equivalente a um controller (framework/servers/user_server.go) e dentro da entidade deveriam ficar somente validações essenciais para regra de negócio. Verificando os campos obrigatórios pra existência da entidade, se estão chegando dentro de ValueObjects válidos (Ex.: Email, CPF, CNPJ, etc).

Porém também é necessário validar se o email é único antes de persistir a entidade, e isso ficaria a cargo de alguma estrutura com acesso ao banco verificar, aí acredito que na camada de aplicação com a ajuda do repositório conseguiria realizar esta validação.

Quais são as opiniões de vocês?

2020-04-10 00:19 UTC, wesleywillians commented
Galera, valeu pela contribuição.

Vamos lá. Quando estamos trabalhando com modelagem de domínios ricos, as regras de negócio e validações sempre ficarão dentro da camada de domínio. A grande sacada é sempre conseguir manter os objetos no estado correto, garantindo sempre a consistência de dados.

Sobre as validações, independente se é para ver se um email está no formato correto ou mesmo se há alguma regra de negócio baseada, as mesmas ficam nas entidades. Lembre-se, o domínio é o coração do software, ele sempre deve estar protegido e ser independente de framework.

Sobre a verificação de email repetidos ou qualquer coisa desse tipo, sem dúvidas, isso é responsabilidade da camada de aplicação.

Acham que estamos alinhados?

2020-04-10 15:19 UTC, mihailov-vf commented
Perfeito, estamos sim!

2020-04-10 19:22 UTC, wesleywillians commented
Pessoal, fiz uma validação básica com o govalidator. Vou fechar essa PR. Mas vou manter a issue aberta para validarmos melhor senha, etc.

2020-04-10 19:22 UTC, closed without merging